# Uncomment the next line to define a global platform for your project
platform :ios, '18.0'

target 'Dependency_managers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dependency_managers
  pod 'SnapKit', '~> 5.7.0'
end
